### ISSUE TITLE
Replace old HTTP connection with newer HTTP client

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/kiwiproject-changelog#21]
I 100% realize you basically copied this from the GitHub version, but we need to use something else other than this Java 1 stuff, like even the new HTTP client that was added in JDK 10 (as preview) and 11 (final). This should be a task for another time, however.

It would also be good to update the POM to specify the Java version is 11 (last night in IntelliJ, the imported project was complaining that I needed to set the language level to 8 -- it was automatically set to 5 for whatever reason, probably b/c the POM didn't make it explicit)

_Originally posted by @sleberknight in https://github.com/chrisrohr/kiwiproject-changelog/pull/20#discussion_r931490184_

**Comment by sleberknight** [comment]
Could try out Ktor ...

**Comment by sleberknight** [comment]
Or use that GitHub for Java library that Pierrot referenced in its docs

**Comment by sleberknight** [comment]
On the other hand, maybe adding yet another library isn't a good idea if we only need to call one or two endpoints.

**Comment by sleberknight** [comment]
Another option is [javalin](https://javalin.io/) which was originally a fork of sparkjava and specifically says it is a "_simple web framework for Java and Kotlin_"

**Comment by sleberknight** [comment]
Ignore last comment...javalin is a _server_ library, not _client_
