### ISSUE TITLE
Extract common code between Gitlab and Github implementations

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/kiwiproject-changelog#22]
I also realize you probably copy and modified the GitHub version...is there enough commonality to extract anything?

_Originally posted by @sleberknight in https://github.com/chrisrohr/kiwiproject-changelog/pull/20#discussion_r931492223_

**Comment by sleberknight** [comment]
Or, we can just remove all the GitLab stuff entirely...

**Comment by sleberknight** [comment]
Closing as "Won't Do" b/c we are removing GitLab code per #130
